CREATE TABLE ROOM (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(32)
);

CREATE TABLE RESERVATION (
    id INT PRIMARY KEY AUTO_INCREMENT,
    startDate DATE NOT NULL,
    endDate DATE,
    ROOM_ID INTEGER,
    CONSTRAINT ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID)
);

